### ISSUE TITLE
Не нашли решения задачи на sqlite

### ISSUE THREAD

**Issue by Romfill007** [FiruzShoev/yandex-praktikum-beta#1]
> В этом задании точно нужно использовать python? "необходимо использовать Python, так как простых SQL запросов будет недостаточно" (c) В гите решение без python.

Не нашли реализацию в репозитории

**Comment by FiruzShoev** [comment]
@Romfill007 это не я писал, а @teposh :)
Но я как раз вот сделал тоже https://github.com/FiruzShoev/yandex-praktikum-beta/blob/master/full-text-search/SQLite/task.sql

**Comment by dwillow** [comment]
@Romfill007, моё (@teposh) решение здесь -
https://github.com/dwillow/praktikum/blob/master/3_sqlite.sql
